<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7871" started-at="2016-06-29T14:26:34Z" finished-at="2016-06-29T14:26:42Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7871" started-at="2016-06-29T14:26:34Z" finished-at="2016-06-29T14:26:42Z">
      <class name="qait.task.gitautomate.CheckInTest">
        <test-method status="FAIL" signature="f(org.openqa.selenium.WebDriver, java.lang.String)[pri:0, instance:qait.task.gitautomate.CheckInTest@6fb1d085]" name="f" duration-ms="5059" started-at="2016-06-29T19:56:37Z" data-provider="test1" finished-at="2016-06-29T19:56:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[FirefoxDriver: firefox on LINUX (790129e6-4324-479f-9468-3fcaed6377af)]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://github.com/jaspal29/Advance]]>
              </value>
            </param>
          </params>
          <exception class="java.io.IOException">
            <message>
              <![CDATA[Cannot run program "/home/jaspalchandramola/Desktop/Clone.sh": error=2, No such file or directory]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.IOException: Cannot run program "/home/jaspalchandramola/Desktop/Clone.sh": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at qait.task.gitautomate.CheckInTest.f(CheckInTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 26 more
]]>
            </full-stacktrace>
          </exception> <!-- java.io.IOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
      </class> <!-- qait.task.gitautomate.CheckInTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
